tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e3e2e0",
        "secondary-container": "#fe9978",
        "on-primary": "#ffffff",
        "surface": "#faf9f7",
        "surface-container": "#efeeec",
        "secondary-fixed": "#ffdbd0",
        "surface-dim": "#dadad8",
        "outline-variant": "#c1c8c2",
        "surface-bright": "#faf9f7",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#414844",
        "on-error": "#ffffff",
        "on-tertiary-container": "#9fa9a3",
        "inverse-primary": "#a5d0b9",
        "error": "#ba1a1a",
        "surface-container-high": "#e9e8e6",
        "on-tertiary-fixed": "#151d1a",
        "inverse-on-surface": "#f1f1ef",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#3f4945",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f3130",
        "primary": "#012d1d",
        "on-primary-fixed-variant": "#274e3d",
        "tertiary": "#1f2825",
        "primary-fixed": "#c1ecd4",
        "surface-variant": "#e3e2e0",
        "outline": "#717973",
        "on-secondary-fixed": "#390b00",
        "tertiary-fixed": "#dbe5df",
        "secondary": "#97472c",
        "secondary-fixed-dim": "#ffb59d",
        "on-background": "#1a1c1b",
        "on-secondary-container": "#772f16",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#86af99",
        "surface-container-low": "#f4f3f1",
        "on-primary-fixed": "#002114",
        "background": "#faf9f7",
        "error-container": "#ffdad6",
        "primary-container": "#1b4332",
        "surface-tint": "#3f6653",
        "on-secondary-fixed-variant": "#793017",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#a5d0b9",
        "tertiary-fixed-dim": "#bfc9c3",
        "tertiary-container": "#353e3a",
        "terracotta": "#97472c",
        "forest-green": "#012d1d",
        "sage-light": "#f4f3f1",
        "info": "#1d4ed8",
        "on-info": "#ffffff",
        "info-container": "#dbeafe",
        "on-info-container": "#1e3a8a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "unit": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "stack-lg": "64px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-xl": "100px"
      },
      fontFamily: {
        "body-md": ["\"Source Serif 4\""],
        "label-md": ["\"Source Serif 4\""],
        "headline-xl-mobile": ["\"Source Serif 4\""],
        "headline-xl": ["\"Source Serif 4\""],
        "headline-lg": ["\"Source Serif 4\""],
        "headline-md": ["\"Source Serif 4\""],
        "headline-sm": ["\"Source Serif 4\""],
        "body-lg": ["\"Source Serif 4\""]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    }
  }
};